name: Update TrueSkill tables

on:
  schedule:
    - cron: "0 22 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run TrueSkill script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      run: python scripts/Trueskill_script.py

    - name: Commit updated results
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add docs/results data/matchs.xlsx
        git commit -m "Auto-update TrueSkill results and backup database" || echo "No changes"
        git push
